In [1]:
import pandas as pd
import torch
from torch_geometric.data import Data

In [3]:
import os
cwd = os.getcwd()

In [4]:
data_path = f'{cwd}\\data\\FB15K237\\test.txt'

In [5]:
df = pd.read_csv(data_path, sep='\t', header=None, names=['src', 'rel', 'dst'])
df.head()

,src,rel,dst
0,/m/08966,/travel/travel_destination/climate./travel/tra...,/m/05lf_
1,/m/01hww_,/music/performance_role/regular_performances./...,/m/01q99h
2,/m/09v3jyg,/film/film/release_date_s./film/film_regional_...,/m/0f8l9c
3,/m/02jx1,/location/location/contains,/m/013t85
4,/m/02jx1,/location/location/contains,/m/0m0bj


In [6]:
nodes = pd.unique(df[['src', 'dst']].values.ravel())
node2idx = {n: i for i, n in enumerate(nodes)}
idx2node = {i: n for n, i in node2idx.items()}

In [7]:
src = df['src'].map(node2idx).values
dst = df['dst'].map(node2idx).values

In [10]:
src

array([   0,    2,    4, ..., 8961, 7072, 9026], shape=(20466,))

In [11]:
dst

array([   1,    3,    5, ..., 2003, 7073,  548], shape=(20466,))

In [8]:
edge_index = torch.tensor(
        [list(src) + list(dst), list(dst) + list(src)], dtype=torch.long
    )
data = Data(edge_index=edge_index)

In [15]:
edge_index

tensor([[   0,    2,    4,  ..., 2003, 7073,  548],
        [   1,    3,    5,  ..., 8961, 7072, 9026]])